// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_oRq1Q7LUWJgxxy6lv-jr9ca7I_aEenE',
    appId: '1:64303259768:web:ad9629edfb83c17e904d8d',
    messagingSenderId: '64303259768',
    projectId: 'financialtool-14c69',
    authDomain: 'financialtool-14c69.firebaseapp.com',
    storageBucket: 'financialtool-14c69.firebasestorage.app',
    measurementId: 'G-QZR4YS33TV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVbvuZUBL2tQaQv_C54HTlVEAlREs-XTk',
    appId: '1:64303259768:ios:a940f5d1d2398592904d8d',
    messagingSenderId: '64303259768',
    projectId: 'financialtool-14c69',
    storageBucket: 'financialtool-14c69.firebasestorage.app',
    iosBundleId: 'com.example.financialPatternDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVbvuZUBL2tQaQv_C54HTlVEAlREs-XTk',
    appId: '1:64303259768:ios:a940f5d1d2398592904d8d',
    messagingSenderId: '64303259768',
    projectId: 'financialtool-14c69',
    storageBucket: 'financialtool-14c69.firebasestorage.app',
    iosBundleId: 'com.example.financialPatternDetector',
  );
}
